# Generated by Django 5.0.2 on 2024-03-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0076_auto_20200826_1553"),
        ("api", "0102_alter_check_kind"),
    ]

    operations = []
